version: "2.0"

services:
  mongodb:
    image: mongodb
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME = root
      - MONGO_INITDB_ROOT_PASSWORD = password
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8999:8999
    restart: always
    volumes:
      - data:/data
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME = root
      - ME_CONFIG_MONGODB_ADMINPASSWORD = password
      - ME_CONFIG_MONGODB_SERVER = mongodb

volumes:
  data: {}

networks:
  default:
    name: mongodb_network
